# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        require_serial: true
        types_or: [python, pyi]
        args: [--line-length=88]
        # when updating black args, also update .vscode/settings.json to match

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        types_or: [cython, pyi, python]
        args: [--profile, black]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: flake8
        description: "`flake8` is a command-line utility for enforcing style consistency across Python projects."
        entry: flake8
        types: [python]
        # when updating flake args, also update .vscode/settings.json or "python.linting.flake8Args" in .devcontainer/devcontainer.json to match
        args: [--max-line-length=88]
        exclude: ^notebooks
        require_serial: true
